name: Varios Steps
on: 
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  variosSteps:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          # 0 significa baixar todo o histórico.
          # Necessário para fazer diff com github.event.before
          fetch-depth: 0

      - name: Say dt_hora
        run: date

      - name: User Push
        run: echo "Usuario do push é ${{ github.actor }}"

      - name: Contar arquivos HTML, CSS e JS enviados no push 
        run: |
          echo "Arquivos enviados neste push:"
          git diff --name-only ${{ github.event.before }} ${{ github.sha }}
          count=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -E '\.html$|\.css$|\.js$' | wc -l)
          echo "Foram enviados $count arquivos HTML, CSS ou JS neste push."
